name: git_diff_in_github_actions
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:
jobs:
  git_diff_in_github_actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cat target.txt
      - run: echo "New data" > target.txt
      - run: cat target.txt
      - run: git branch
      - run: git status
      - run: git diff
  swiftlint_help:
    runs-on: macos-latest
    steps:
      - run: swiftlint help
      - run: swiftlint help lint
