name: git_diff_in_github_actions
on:
  push:
    branch: main
  pull_request:
    branch: main
  workflow_dispatch:
jobs:
  git_diff_in_github_actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cat target.txt
      - run: echo "New data\n" > target.txt
      - run: cat target.txt
      - run: git branch
      - run: git status
      - run: git diff
